apiVersion: v3
kind: service
metadata:
  name: my-animals
  displayName: My Animals
  tags:
    - owner:frontdesk
    - support:deskjockies
  links:
    - name: animal support runbook
      type: runbook
      url: https://www.google.com
    - name: Home Page
      type: runbook
      url: http://my-animals.localhost
spec:
  components:
    - service:animals-2
    - service:listing-cats
